import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Baseline migration that captures the schema as of 2026-04-27 (commit be45434).
 * Written idempotently (IF NOT EXISTS) so it is safe to run against:
 *   - a fresh database (creates everything)
 *   - the existing prod database (no-op, since prod was already brought to this
 *     state manually before this migration was introduced)
 *
 * Future schema changes MUST be added as new migrations, generated via
 * `npm run migration:generate -- src/migrations/<name>` and committed alongside
 * the entity change. Do NOT edit this file.
 */
export class InitialBaseline1714230000000 implements MigrationInterface {
  name = 'InitialBaseline1714230000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "users" (
        "id"           SERIAL PRIMARY KEY,
        "username"     varchar NOT NULL,
        "passwordHash" varchar NOT NULL,
        "role"         varchar NOT NULL DEFAULT 'user',
        "preferences"  jsonb,
        "createdAt"    TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_users_username" UNIQUE ("username")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "patients" (
        "id"        SERIAL PRIMARY KEY,
        "rut"       varchar NOT NULL,
        "firstName" varchar NOT NULL,
        "lastName"  varchar NOT NULL,
        "birthDate" date NOT NULL,
        "gender"    varchar NOT NULL,
        "phone"     varchar,
        "address"   varchar,
        "status"    varchar NOT NULL DEFAULT 'active',
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_patients_rut" UNIQUE ("rut")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "curaciones" (
        "id"             SERIAL PRIMARY KEY,
        "patientId"      integer NOT NULL,
        "type"           varchar NOT NULL,
        "date"           date NOT NULL,
        "quantity"       integer NOT NULL DEFAULT 1,
        "observations"   text,
        "bootDelivered"  boolean NOT NULL DEFAULT false,
        "createdAt"      TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_curaciones_patient"
          FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "appointments" (
        "id"          SERIAL PRIMARY KEY,
        "patientId"   integer NOT NULL,
        "curacionId"  integer,
        "date"        date NOT NULL,
        "time"        varchar NOT NULL,
        "createdAt"   TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_appointments_date_time" UNIQUE ("date", "time"),
        CONSTRAINT "UQ_appointments_curacion" UNIQUE ("curacionId"),
        CONSTRAINT "FK_appointments_patient"
          FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_appointments_curacion"
          FOREIGN KEY ("curacionId") REFERENCES "curaciones"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "monthly_cycles" (
        "id"        SERIAL PRIMARY KEY,
        "year"      integer NOT NULL,
        "month"     integer NOT NULL,
        "startDate" date NOT NULL,
        "endDate"   date NOT NULL,
        CONSTRAINT "UQ_monthly_cycles_year_month" UNIQUE ("year", "month")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "patient_status_changes" (
        "id"            SERIAL PRIMARY KEY,
        "patientId"     integer NOT NULL,
        "type"          varchar NOT NULL,
        "performedById" integer NOT NULL,
        "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_psc_patient"
          FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_psc_user"
          FOREIGN KEY ("performedById") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "curacion_edits" (
        "id"          SERIAL PRIMARY KEY,
        "curacionId"  integer NOT NULL,
        "editedById"  integer NOT NULL,
        "reason"      text NOT NULL,
        "createdAt"   TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_ce_curacion"
          FOREIGN KEY ("curacionId") REFERENCES "curaciones"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_ce_user"
          FOREIGN KEY ("editedById") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "audit_logs" (
        "id"        SERIAL PRIMARY KEY,
        "userId"    integer NOT NULL,
        "username"  varchar NOT NULL,
        "action"    varchar NOT NULL,
        "entity"    varchar NOT NULL,
        "entityId"  integer NOT NULL,
        "payload"   jsonb,
        "ipAddress" varchar,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_audit_user"
          FOREIGN KEY ("userId") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "consent_signatures" (
        "id"             SERIAL PRIMARY KEY,
        "patientId"      integer NOT NULL,
        "witnessedById"  integer NOT NULL,
        "filename"       varchar NOT NULL,
        "consentText"    text,
        "signedAt"       TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_consent_patient"
          FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_consent_witness"
          FOREIGN KEY ("witnessedById") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "wound_notes" (
        "id"            SERIAL PRIMARY KEY,
        "curacionId"    integer NOT NULL,
        "recordedById"  integer NOT NULL,
        "woundWidth"    decimal(5,2),
        "woundLength"   decimal(5,2),
        "woundArea"     decimal(7,2),
        "woundColor"    varchar,
        "exudateLevel"  varchar,
        "healingStage"  varchar,
        "notes"         text,
        "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_wn_curacion"
          FOREIGN KEY ("curacionId") REFERENCES "curaciones"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_wn_user"
          FOREIGN KEY ("recordedById") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "wound_photos" (
        "id"            SERIAL PRIMARY KEY,
        "patientId"     integer NOT NULL,
        "uploadedById"  integer NOT NULL,
        "filename"      varchar NOT NULL,
        "description"   text,
        "photoDate"     date NOT NULL,
        "createdAt"     TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "FK_wp_patient"
          FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_wp_user"
          FOREIGN KEY ("uploadedById") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`ALTER TABLE "users"      ADD COLUMN IF NOT EXISTS "preferences"   jsonb`);
    await queryRunner.query(`ALTER TABLE "curaciones" ADD COLUMN IF NOT EXISTS "bootDelivered" boolean NOT NULL DEFAULT false`);
  }

  public async down(): Promise<void> {
    throw new Error(
      'Reverting the baseline migration is not supported. ' +
        'Restore from a database backup instead.',
    );
  }
}
